name: Build Storybook

on: [push]

jobs:
  comment-storybook-url:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 438
          body: |
            Storybook preview: https://quran.github.io/quran.com-frontend-next/storybook/{{ github.head_ref }}/
